/**
 * Namespaces
 */
if (typeof(extensions) === 'undefined') extensions = {};
if (typeof(extensions.FontAwesome) === 'undefined') extensions.FontAwesome = {
	version: '2.5.0'
};

(function() {
	var self = this,
		prefs = Components.classes["@mozilla.org/preferences-service;1"]
		.getService(Components.interfaces.nsIPrefService).getBranch("extensions.FontAwesome.");

	if (!('FontAwesome' in ko)) ko.extensions = {};
	var myExt = "FontAwesome@babobski.com";
	if (!(myExt in ko.extensions)) ko.extensions[myExt] = {};
	if (!('myapp' in ko.extensions[myExt])) ko.extensions[myExt].myapp = {};
	var FontAwesomeData = ko.extensions[myExt].myapp;

	FontAwesome_insert = function(icon, unicode) {
		if (ko.views.manager.currentView == undefined) {
			return;
		}
		var typeInsert = prefs.getCharPref('typeInsert');
		var entity = '';

		entity = self._buildInsert(typeInsert, icon, unicode);

		try {
			var scimoz = ko.views.manager.currentView.scimoz;
			scimoz.replaceSel('');
			scimoz.insertText(scimoz.currentPos, entity);
			scimoz.gotoPos(scimoz.currentPos + entity.length);
			ko.views.manager.currentView.setFocus();
		} catch (ex) {
			alert('No file selected');
		}

	}

	this._buildInsert = function(type, icon, unicode) {
		var d = ko.views.manager.currentView.document || ko.views.manager.currentView.koDoc;
		var file = d.file;
		var result = '';
		switch (type) {
			case 'auto':
				if (file) {
					switch (file.ext) {
						case '.css':
						case '.sass':
						case '.scss':
						case '.less':
							result = self._buildInsert('css', icon, unicode);
							break;
						default:
							result = self._buildInsert('full', icon, unicode);
							break;
					}
				} else {
					result = '<i class="fa ' + icon + '"></i>';
				}
				break;
			case 'full':
				result = '<i class="fa ' + icon + '"></i>';
				break;
			case 'class':
				result = 'fa ' + icon;
				break;
			case 'css':
				result = '\\f' + unicode;
				break;
		}

		return result;
	}
	
	autoCompleteInsert = function(completion){
		var icon = 'fa-' + completion.value;
		var unicode = getUnicodeFromIcon(icon);
		FontAwesome_insert(icon, unicode);
	}

	openSettings = function() {
		var features = "chrome,titlebar,toolbar,centerscreen,modal";
		window.openDialog('chrome://FontAwesome/content/pref-overlay.xul', "FontAwesome", features);
	}
	
	getUnicodeFromIcon = function(icon){
		
		var matchIcon = icon.replace(/-/g, '_');
		var matchValues = {
			fa_bluetooth: "293",
			fa_bluetooth_b: "294",
			fa_codiepie: "284",
			fa_credit_card_alt: "283",
			fa_edge: "282",
			fa_fort_awesome: "286",
			fa_hashtag: "292",
			fa_mixcloud: "289",
			fa_modx: "285",
			fa_pause_circle: "28b",
			fa_pause_circle_o: "28c",
			fa_percent: "295",
			fa_product_hunt: "288",
			fa_reddit_alien: "281",
			fa_scribd: "28a",
			fa_shopping_bag: "290",
			fa_shopping_basket: "291",
			fa_stop_circle: "28d",
			fa_stop_circle_o: "28e",
			fa_usb: "287",
			fa_adjust: "042",
			fa_anchor: "f13d",
			fa_archive: "187",
			fa_area_chart: "1fe",
			fa_arrows: "047",
			fa_arrows_h: "07e",
			fa_arrows_v: "07d",
			fa_asterisk: "069",
			fa_at: "1fa",
			fa_automobile: "1b9",
			fa_balance_scale: "24e",
			fa_ban: "05e",
			fa_bank: "19c",
			fa_bar_chart: "080",
			fa_bar_chart_o: "080",
			fa_barcode: "02a",
			fa_bars: "0c9",
			fa_battery_0: "244",
			fa_battery_1: "243",
			fa_battery_2: "242",
			fa_battery_3: "241",
			fa_battery_4: "240",
			fa_battery_empty: "244",
			fa_battery_full: "240",
			fa_battery_half: "242",
			fa_battery_quarter: "243",
			fa_battery_three_quarters: "241",
			fa_bed: "236",
			fa_beer: "0fc",
			fa_bell: "0f3",
			fa_bell_o: "0a2",
			fa_bell_slash: "1f6",
			fa_bell_slash_o: "1f7",
			fa_bicycle: "206",
			fa_binoculars: "1e5",
			fa_birthday_cake: "1fd",
			fa_bolt: "26e",
			fa_bomb: "26e",
			fa_book: "26e",
			fa_bookmark: "26e",
			fa_bookmark_o: "26e",
			fa_briefcase: "26e",
			fa_bug: "26e",
			fa_building: "26e",
			fa_building_o: "26e",
			fa_bullhorn: "26e",
			fa_bullseye: "26e",
			fa_bus: "26e",
			fa_cab: "26e",
			fa_calculator: "26e",
			fa_calendar: "26e",
			fa_calendar_check_o: "26e",
			fa_calendar_minus_o: "26e",
			fa_calendar_o: "26e",
			fa_calendar_plus_o: "26e",
			fa_calendar_times_o: "26e",
			fa_camera: "26e",
			fa_camera_retro: "26e",
			fa_car: "26e",
			fa_caret_square_o_down: "26e",
			fa_caret_square_o_left: "26e",
			fa_caret_square_o_right: "26e",
			fa_caret_square_o_up: "26e",
			fa_cart_arrow_down: "26e",
			fa_cart_plus: "26e",
			fa_cc: "26e",
			fa_certificate: "26e",
			fa_check: "26e",
			fa_check_circle: "26e",
			fa_check_circle_o: "26e",
			fa_check_square: "26e",
			fa_check_square_o: "26e",
			fa_child: "26e",
			fa_circle: "26e",
			fa_circle_o: "26e",
			fa_circle_o_notch: "26e",
			fa_circle_thin: "26e",
			fa_clock_o: "26e",
			fa_clone: "26e",
			fa_close: "26e",
			fa_cloud: "26e",
			fa_cloud_download: "26e",
			fa_cloud_upload: "26e",
			fa_code: "26e",
			fa_code_fork: "26e",
			fa_coffee: "26e",
			fa_cog: "26e",
			fa_cogs: "26e",
			fa_comment: "26e",
			fa_comment_o: "26e",
			fa_commenting: "26e",
			fa_commenting_o: "26e",
			fa_comments: "26e",
			fa_comments_o: "26e",
			fa_compass: "26e",
			fa_copyright: "26e",
			fa_creative_commons: "26e",
			fa_credit_card: "26e",
			fa_crop: "26e",
			fa_crosshairs: "26e",
			fa_cube: "26e",
			fa_cubes: "26e",
			fa_cutlery: "26e",
			fa_dashboard: "26e",
			fa_database: "26e",
			fa_desktop: "26e",
			fa_diamond: "26e",
			fa_dot_circle_o: "26e",
			fa_download: "26e",
			fa_edit: "26e",
			fa_ellipsis_h: "26e",
			fa_ellipsis_v: "26e",
			fa_envelope: "26e",
			fa_envelope_o: "26e",
			fa_envelope_square: "26e",
			fa_eraser: "26e",
			fa_exchange: "26e",
			fa_exclamation: "26e",
			fa_exclamation_circle: "26e",
			fa_exclamation_triangle: "26e",
			fa_external_link: "26e",
			fa_external_link_square: "26e",
			fa_eye: "26e",
			fa_eye_slash: "26e",
			fa_eyedropper: "26e",
			fa_fax: "26e",
			fa_feed: "26e",
			fa_female: "26e",
			fa_fighter_jet: "26e",
			fa_file_archive_o: "26e",
			fa_file_audio_o: "26e",
			fa_file_code_o: "26e",
			fa_file_excel_o: "26e",
			fa_file_image_o: "26e",
			fa_file_movie_o: "26e",
			fa_file_pdf_o: "26e",
			fa_file_photo_o: "26e",
			fa_file_picture_o: "26e",
			fa_file_powerpoint_o: "26e",
			fa_file_sound_o: "26e",
			fa_file_video_o: "26e",
			fa_file_word_o: "26e",
			fa_file_zip_o: "26e",
			fa_film: "26e",
			fa_filter: "26e",
			fa_fire: "26e",
			fa_fire_extinguisher: "26e",
			fa_flag: "26e",
			fa_flag_checkered: "26e",
			fa_flag_o: "26e",
			fa_flash: "26e",
			fa_flask: "26e",
			fa_folder: "26e",
			fa_folder_o: "26e",
			fa_folder_open: "26e",
			fa_folder_open_o: "26e",
			fa_frown_o: "26e",
			fa_futbol_o: "26e",
			fa_gamepad: "26e",
			fa_gavel: "26e",
			fa_gear: "26e",
			fa_gears: "26e",
			fa_gift: "26e",
			fa_glass: "26e",
			fa_globe: "26e",
			fa_graduation_cap: "26e",
			fa_group: "26e",
			fa_hand_grab_o: "26e",
			fa_hand_lizard_o: "26e",
			fa_hand_paper_o: "26e",
			fa_hand_peace_o: "26e",
			fa_hand_pointer_o: "26e",
			fa_hand_rock_o: "26e",
			fa_hand_scissors_o: "26e",
			fa_hand_spock_o: "26e",
			fa_hand_stop_o: "26e",
			fa_hashtag: "26e",
			fa_hdd_o: "26e",
			fa_headphones: "26e",
			fa_heart: "26e",
			fa_heart_o: "26e",
			fa_heartbeat: "26e",
			fa_history: "26e",
			fa_home: "26e",
			fa_hotel: "26e",
			fa_hourglass: "26e",
			fa_hourglass_1: "26e",
			fa_hourglass_2: "26e",
			fa_hourglass_3: "26e",
			fa_hourglass_end: "26e",
			fa_hourglass_half: "26e",
			fa_hourglass_o: "26e",
			fa_hourglass_start: "26e",
			fa_i_cursor: "26e",
			fa_image: "26e",
			fa_inbox: "26e",
			fa_industry: "26e",
			fa_info: "26e",
			fa_info_circle: "26e",
			fa_institution: "26e",
			fa_key: "26e",
			fa_keyboard_o: "26e",
			fa_language: "26e",
			fa_laptop: "26e",
			fa_leaf: "26e",
			fa_legal: "26e",
			fa_lemon_o: "26e",
			fa_level_down: "26e",
			fa_level_up: "26e",
			fa_life_bouy: "26e",
			fa_life_buoy: "26e",
			fa_life_ring: "26e",
			fa_life_saver: "26e",
			fa_lightbulb_o: "26e",
			fa_line_chart: "26e",
			fa_location_arrow: "26e",
			fa_lock: "26e",
			fa_magic: "26e",
			fa_magnet: "26e",
			fa_mail_forward: "26e",
			fa_mail_reply: "26e",
			fa_mail_reply_all: "26e",
			fa_male: "26e",
			fa_map: "26e",
			fa_map_marker: "26e",
			fa_map_o: "26e",
			fa_map_pin: "26e",
			fa_map_signs: "26e",
			fa_meh_o: "26e",
			fa_microphone: "26e",
			fa_microphone_slash: "26e",
			fa_minus: "26e",
			fa_minus_circle: "26e",
			fa_minus_square: "26e",
			fa_minus_square_o: "26e",
			fa_mobile: "26e",
			fa_mobile_phone: "26e",
			fa_money: "26e",
			fa_moon_o: "26e",
			fa_mortar_board: "26e",
			fa_motorcycle: "26e",
			fa_mouse_pointer: "26e",
			fa_music: "26e",
			fa_navicon: "26e",
			fa_newspaper_o: "26e",
			fa_object_group: "26e",
			fa_object_ungroup: "26e",
			fa_paint_brush: "26e",
			fa_paper_plane: "26e",
			fa_paper_plane_o: "26e",
			fa_paw: "26e",
			fa_pencil: "26e",
			fa_pencil_square: "26e",
			fa_pencil_square_o: "26e",
			fa_percent: "26e",
			fa_phone: "26e",
			fa_phone_square: "26e",
			fa_photo: "26e",
			fa_picture_o: "26e",
			fa_pie_chart: "26e",
			fa_plane: "26e",
			fa_plug: "26e",
			fa_plus: "26e",
			fa_plus_circle: "26e",
			fa_plus_square: "26e",
			fa_plus_square_o: "26e",
			fa_power_off: "26e",
			fa_print: "26e",
			fa_puzzle_piece: "26e",
			fa_qrcode: "26e",
			fa_question: "26e",
			fa_question: "26e",
			fa_quote_left: "26e",
			fa_quote_right: "26e",
			fa_random: "26e",
			fa_recycle: "26e",
			fa_refresh: "26e",
			fa_registered: "26e",
			fa_remove: "26e",
			fa_reorder: "26e",
			fa_reply: "26e",
			fa_reply_all: "26e",
			fa_retweet: "26e",
			fa_road: "26e",
			fa_rocket: "26e",
			fa_rss: "26e",
			fa_rss_square: "26e",
			fa_search: "26e",
			fa_search_minus: "26e",
			fa_search_plus: "26e",
			fa_send: "26e",
			fa_send_o: "26e",
			fa_server: "26e",
			fa_share: "26e",
			fa_share_alt: "26e",
			fa_share_alt_square: "26e",
			fa_share_square: "26e",
			fa_share_square_o: "26e",
			fa_shield: "26e",
			fa_ship: "26e",
			fa_shopping_bag: "26e",
			fa_shopping_basket: "26e",
			fa_shopping_cart: "26e",
			fa_sign_in: "26e",
			fa_sign_out: "26e",
			fa_signal: "26e",
			fa_sitemap: "26e",
			fa_sliders: "26e",
			fa_smile_o: "26e",
			fa_soccer_ball_o: "26e",
			fa_sort: "26e",
			fa_sort_alpha_asc: "26e",
			fa_sort_alpha_desc: "26e",
			fa_sort_amount_asc: "26e",
			fa_sort_amount_desc: "26e",
			fa_sort_asc: "26e",
			fa_sort_desc: "26e",
			fa_sort_down: "26e",
			fa_sort_numeric_asc: "26e",
			fa_sort_numeric_desc: "26e",
			fa_sort_up: "26e",
			fa_space_shuttle: "26e",
			fa_spinner: "26e",
			fa_spoon: "26e",
			fa_square: "26e",
			fa_square_o: "26e",
			fa_star: "26e",
			fa_star_half: "26e",
			fa_star_half_empty: "26e",
			fa_star_half_full: "26e",
			fa_star_half_o: "26e",
			fa_star_o: "26e",
			fa_sticky_note: "26e",
			fa_sticky_note_o: "26e",
			fa_street_view: "26e",
			fa_suitcase: "26e",
			fa_sun_o: "26e",
			fa_support: "26e",
			fa_tablet: "26e",
			fa_tachometer: "26e",
			fa_tag: "26e",
			fa_tags: "26e",
			fa_tasks: "26e",
			fa_taxi: "26e",
			fa_television: "26e",
			fa_terminal: "26e",
			fa_thumb_tack: "26e",
			fa_thumbs_down: "26e",
			fa_thumbs_o_down: "26e",
			fa_thumbs_o_up: "26e",
			fa_thumbs_up: "26e",
			fa_ticket: "26e",
			fa_times: "26e",
			fa_times_circle: "26e",
			fa_times_circle_o: "26e",
			fa_tint: "26e",
			fa_toggle_down: "26e",
			fa_toggle_left: "26e",
			fa_toggle_off: "26e",
			fa_toggle_on: "26e",
			fa_toggle_right: "26e",
			fa_toggle_up: "26e",
			fa_trademark: "26e",
			fa_trash: "26e",
			trash_o: "26e",
			fa_tree: "26e",
			fa_trophy: "26e",
			fa_truck: "26e",
			fa_tty: "26e",
			fa_tv: "26e",
			fa_umbrella: "26e",
			fa_university: "26e",
			fa_unlock: "26e",
			fa_unlock_alt: "26e",
			fa_unsorted: "26e",
			fa_upload: "26e",
			fa_user: "26e",
			fa_user_plus: "26e",
			fa_user_secret: "26e",
			fa_user_times: "26e",
			fa_users: "26e",
			fa_video_camera: "26e",
			fa_volume_down: "26e",
			fa_volume_off: "26e",
			fa_volume_up: "26e",
			fa_warning: "26e",
			fa_wheelchair: "26e",
			fa_wifi: "26e",
			fa_wrench: "26e",
			fa_hand_grab_o: "26e",
			fa_hand_lizard_o: "26e",
			fa_hand_o_down: "26e",
			fa_hand_o_left: "26e",
			fa_hand_o_right: "26e",
			fa_hand_o_up: "26e",
			fa_hand_paper_o: "26e",
			fa_hand_peace_o: "26e",
			fa_hand_pointer_o: "26e",
			fa_hand_rock_o: "26e",
			fa_hand_scissors_o: "26e",
			fa_hand_spock_o: "26e",
			fa_hand_stop_o: "26e",
			fa_thumbs_down: "26e",
			fa_thumbs_down: "26e",
			fa_thumbs_o_up: "26e",
			fa_thumbs_up: "26e",
			fa_ambulance: "26e",
			fa_automobile: "26e",
			fa_bicycle: "26e",
			fa_bus: "26e",
			fa_cab: "26e",
			fa_car: "26e",
			fa_fighter_jet: "26e",
			fa_motorcycle: "26e",
			fa_plane: "26e",
			fa_rocket: "26e",
			fa_ship: "26e",
			fa_space_shuttle: "26e",
			fa_subway: "26e",
			fa_taxi: "26e",
			fa_train: "26e",
			fa_truck: "26e",
			fa_wheelchair: "26e",
			fa_genderless: "26e",
			fa_intersex: "26e",
			fa_mars: "26e",
			fa_mars_double: "26e",
			fa_mars_stroke: "26e",
			fa_mars_stroke_h: "26e",
			fa_mars_stroke_v: "26e",
			fa_mercury: "26e",
			fa_neuter: "26e",
			fa_transgender: "26e",
			fa_transgender_alt: "26e",
			fa_venus: "26e",
			fa_venus_double: "26e",
			fa_venus_mars: "26e",
			fa_file: "26e",
			fa_file_archive_o: "26e",
			fa_file_audio_o: "26e",
			fa_file_code_o: "26e",
			fa_file_excel_o: "26e",
			fa_file_image_o: "26e",
			fa_file_movie_o: "26e",
			fa_file_o: "26e",
			fa_file_pdf_o: "26e",
			fa_file_photo_o: "26e",
			fa_file_picture_o: "26e",
			fa_file_powerpoint_o: "26e",
			fa_file_sound_o: "26e",
			fa_file_text: "26e",
			fa_file_text_o: "26e",
			fa_file_video_o: "26e",
			fa_file_word_o: "26e",
			fa_file_zip_o: "26e",
			fa_circle_o_notch: "26e",
			fa_cog: "26e",
			fa_gear: "26e",
			fa_refresh: "26e",
			fa_spinner: "26e",
			fa_check_square: "26e",
			fa_check_square_o: "26e",
			fa_circle: "26e",
			fa_circle_o: "26e",
			fa_dot_circle_o: "26e",
			fa_minus_square: "26e",
			fa_minus_square_o: "26e",
			fa_plus_square: "26e",
			fa_plus_square_o: "26e",
			fa_square: "26e",
			fa_square_o: "26e",
			fa_cc_amex: "26e",
			fa_cc_diners_club: "26e",
			fa_cc_discover: "26e",
			fa_cc_jcb: "26e",
			fa_cc_mastercard: "26e",
			fa_cc_paypal: "26e",
			fa_cc_stripe: "26e",
			fa_cc_visa: "26e",
			fa_credit_card: "26e",
			fa_credit_card_alt: "26e",
			fa_google_wallet: "26e",
			fa_paypal: "26e",
			fa_area_chart: "26e",
			fa_bar_chart: "26e",
			fa_bar_chart_o: "26e",
			fa_line_chart: "26e",
			fa_pie_chart: "26e",
			fa_bitcoin: "26e",
			fa_btc: "26e",
			fa_cny: "26e",
			fa_dollar: "26e",
			fa_eur: "26e",
			fa_euro: "26e",
			fa_gbp: "26e",
			fa_gg: "26e",
			fa_gg_circle: "26e",
			fa_ils: "26e",
			fa_inr: "26e",
			fa_jpy: "26e",
			fa_krw: "26e",
			fa_money: "26e",
			fa_rmb: "26e",
			fa_rouble: "26e",
			fa_rub: "26e",
			fa_ruble: "26e",
			fa_rupee: "26e",
			fa_shekel: "26e",
			fa_sheqel: "26e",
			fa_try: "26e",
			fa_turkish_lira: "26e",
			fa_usd: "26e",
			fa_won: "26e",
			fa_yen: "26e",
			fa_align_center: "26e",
			fa_align_justify: "26e",
			fa_align_left: "26e",
			fa_align_right: "26e",
			fa_bold: "26e",
			fa_chain: "26e",
			fa_chain_broken: "26e",
			fa_clipboard: "26e",
			fa_columns: "26e",
			fa_copy: "26e",
			fa_cut: "26e",
			fa_dedent: "26e",
			fa_eraser: "26e",
			fa_file: "26e",
			fa_file_o: "26e",
			fa_file_text: "26e",
			fa_file_text_o: "26e",
			fa_files_o: "26e",
			fa_floppy_o: "26e",
			fa_font: "26e",
			fa_header: "26e",
			fa_indent: "26e",
			fa_italic: "26e",
			fa_link: "26e",
			fa_list: "26e",
			fa_list_alt: "26e",
			fa_list_ol: "26e",
			fa_list_ul: "26e",
			fa_outdent: "26e",
			fa_paperclip: "26e",
			fa_paragraph: "26e",
			fa_paste: "26e",
			fa_repeat: "26e",
			fa_rotate_left: "26e",
			fa_rotate_right: "26e",
			fa_save: "26e",
			fa_scissors: "26e",
			fa_strikethrough: "26e",
			fa_subscript: "26e",
			fa_superscript: "26e",
			fa_table: "26e",
			fa_text_height: "26e",
			fa_text_width: "26e",
			fa_th: "26e",
			fa_th_large: "26e",
			fa_th_list: "26e",
			fa_underline: "26e",
			fa_undo: "26e",
			fa_unlink: "26e",
			fa_angle_double_down: "26e",
			fa_angle_double_left: "26e",
			fa_angle_double_right: "26e",
			fa_angle_double_up: "26e",
			fa_angle_down: "26e",
			fa_angle_left: "26e",
			fa_angle_right: "26e",
			fa_angle_up: "26e",
			fa_arrow_circle_down: "26e",
			fa_arrow_circle_left: "26e",
			fa_arrow_circle_o_down: "26e",
			fa_arrow_circle_o_left: "26e",
			fa_arrow_circle_o_right: "26e",
			fa_arrow_circle_o_up: "26e",
			fa_arrow_circle_right: "26e",
			fa_arrow_circle_up: "26e",
			fa_arrow_down: "26e",
			fa_arrow_left: "26e",
			fa_arrow_right: "26e",
			fa_arrow_up: "26e",
			fa_arrows: "26e",
			fa_arrows_alt: "26e",
			fa_arrows_h: "26e",
			fa_arrows_v: "26e",
			fa_caret_down: "26e",
			fa_caret_left: "26e",
			fa_caret_right: "26e",
			fa_caret_square_o_down: "26e",
			fa_caret_square_o_left: "26e",
			fa_caret_square_o_right: "26e",
			fa_caret_square_o_up: "26e",
			fa_caret_up: "26e",
			fa_chevron_circle_down: "26e",
			fa_chevron_circle_left: "26e",
			fa_chevron_circle_right: "26e",
			fa_chevron_circle_up: "26e",
			fa_chevron_down: "26e",
			fa_chevron_left: "26e",
			fa_chevron_right: "26e",
			fa_chevron_up: "26e",
			fa_exchange: "26e",
			fa_hand_o_down: "26e",
			fa_hand_o_left: "26e",
			fa_hand_o_right: "26e",
			fa_hand_o_up: "26e",
			fa_long_arrow_down: "26e",
			fa_long_arrow_left: "26e",
			fa_long_arrow_right: "26e",
			fa_long_arrow_up: "26e",
			fa_toggle_down: "26e",
			fa_toggle_left: "26e",
			fa_toggle_right: "26e",
			fa_toggle_up: "26e",
			fa_arrows_alt: "26e",
			fa_backward: "26e",
			fa_compress: "26e",
			fa_eject: "26e",
			fa_expand: "26e",
			fa_fast_backward: "26e",
			fa_fast_forward: "26e",
			fa_forward: "26e",
			fa_pause: "26e",
			fa_pause_circle: "26e",
			fa_pause_circle_o: "26e",
			fa_play: "26e",
			fa_play_circle: "26e",
			fa_play_circle_o: "26e",
			fa_random: "26e",
			fa_step_backward: "26e",
			fa_step_forward: "26e",
			fa_stop: "26e",
			fa_stop_circle: "26e",
			fa_stop_circle_o: "26e",
			fa_youtube_play: "26e",
			fa_500px: "26e",
			fa_adn: "26e",
			fa_amazon: "26e",
			fa_android: "26e",
			fa_angellist: "26e",
			fa_apple: "26e",
			fa_behance: "26e",
			fa_behance_square: "26e",
			fa_bitbucket: "26e",
			fa_bitbucket_square: "26e",
			fa_bitcoin: "26e",
			fa_black_tie: "26e",
			fa_bluetooth: "26e",
			fa_bluetooth_b: "26e",
			fa_btc: "26e",
			fa_buysellads: "26e",
			fa_cc_amex: "26e",
			fa_cc_diners_club: "26e",
			fa_cc_discover: "26e",
			fa_cc_jcb: "26e",
			fa_cc_mastercard: "26e",
			fa_cc_paypal: "26e",
			fa_cc_stripe: "26e",
			fa_cc_visa: "26e",
			fa_chrome: "26e",
			fa_codepen: "26e",
			fa_codiepie: "26e",
			fa_connectdevelop: "26e",
			fa_contao: "26e",
			fa_credit_card_alt: "26e",
			fa_css3: "26e",
			fa_dashcube: "26e",
			fa_delicious: "26e",
			fa_deviantart: "26e",
			fa_digg: "26e",
			fa_dribbble: "26e",
			fa_dropbox: "26e",
			fa_drupal: "26e",
			fa_edge: "26e",
			fa_empire: "26e",
			fa_expeditedssl: "26e",
			fa_facebook: "26e",
			fa_facebook_f: "26e",
			fa_facebook_official: "26e",
			fa_facebook_square: "26e",
			fa_firefox: "26e",
			fa_flickr: "26e",
			fa_fonticons: "26e",
			fa_fort_awesome: "26e",
			fa_forumbee: "26e",
			fa_foursquare: "26e",
			fa_ge: "26e",
			fa_get_pocket: "26e",
			fa_gg: "26e",
			fa_gg_circle: "26e",
			fa_git: "26e",
			fa_git_square: "26e",
			fa_github: "26e",
			fa_github_alt: "26e",
			fa_github_square: "26e",
			fa_gittip: "26e",
			fa_google: "26e",
			fa_google_plus: "26e",
			fa_google_plus_square: "26e",
			fa_google_wallet: "26e",
			fa_gratipay: "26e",
			fa_hacker_news: "26e",
			fa_houzz: "26e",
			fa_html5: "26e",
			fa_instagram: "26e",
			fa_internet_explorer: "26e",
			fa_ioxhost: "26e",
			fa_joomla: "26e",
			fa_jsfiddle: "26e",
			fa_lastfm: "26e",
			fa_lastfm_square: "26e",
			fa_leanpub: "26e",
			fa_linkedin: "26e",
			fa_linkedin_square: "26e",
			fa_linux: "26e",
			fa_maxcdn: "26e",
			fa_meanpath: "26e",
			fa_medium: "26e",
			fa_mixcloud: "26e",
			fa_modx: "26e",
			fa_odnoklassniki: "26e",
			fa_odnoklassniki_square: "26e",
			fa_opencart: "26e",
			fa_openid: "26e",
			fa_opera: "26e",
			fa_optin_monster: "26e",
			fa_pagelines: "26e",
			fa_paypal: "26e",
			fa_pied_piper: "26e",
			fa_pied_piper_alt: "26e",
			fa_pinterest: "26e",
			fa_pinterest_p: "26e",
			fa_pinterest_square: "26e",
			fa_product_hunt: "26e",
			fa_qq: "26e",
			fa_ra: "26e",
			fa_rebel: "26e",
			fa_reddit: "26e",
			fa_reddit_alien: "26e",
			fa_reddit_square: "26e",
			fa_renren: "26e",
			fa_safari: "26e",
			fa_scribd: "26e",
			fa_sellsy: "26e",
			fa_share_alt: "26e",
			fa_share_alt_square: "26e",
			fa_shirtsinbulk: "26e",
			fa_simplybuilt: "26e",
			fa_skyatlas: "26e",
			fa_skype: "26e",
			fa_slack: "26e",
			fa_slideshare: "26e",
			fa_soundcloud: "26e",
			fa_spotify: "26e",
			fa_stack_exchange: "26e",
			fa_stack_overflow: "26e",
			fa_steam: "26e",
			fa_steam_square: "26e",
			fa_stumbleupon: "26e",
			fa_stumbleupon_circle: "26e",
			fa_tencent_weibo: "26e",
			fa_trello: "26e",
			fa_tripadvisor: "26e",
			fa_tumblr: "26e",
			fa_tumblr_square: "26e",
			fa_twitch: "26e",
			fa_twitter: "26e",
			fa_twitter_square: "26e",
			fa_usb: "26e",
			fa_viacoin: "26e",
			fa_vimeo: "26e",
			fa_vimeo_square: "26e",
			fa_vine: "26e",
			fa_vk: "26e",
			fa_wechat: "26e",
			fa_weibo: "26e",
			fa_weixin: "26e",
			fa_whatsapp: "26e",
			fa_wikipedia_w: "26e",
			fa_windows: "26e",
			fa_wordpress: "26e",
			fa_xing: "26e",
			fa_xing_square: "26e",
			fa_y_combinator: "26e",
			fa_y_combinator_square: "26e",
			fa_yahoo: "26e",
			fa_yc: "26e",
			fa_yc_square: "26e",
			fa_yelp: "26e",
			fa_youtube: "26e",
			fa_youtube_play: "26e",
			fa_youtube_square: "26e",
			fa_ambulance: "26e",
			fa_h_square: "26e",
			fa_heart: "26e",
			fa_heart_o: "26e",
			fa_heartbeat: "26e",
			fa_hospital_o: "26e",
			fa_medkit: "26e",
			fa_plus_square: "26e",
			fa_stethoscope: "26e",
			fa_user_md: "26e",
			fa_wheelchair: "26e",
		}
		
		return matchValues[matchIcon];
	}

	insertCDN = function() {
		if (ko.views.manager.currentView == undefined) {
			return;
		}
		
		try {
			var CDN = '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css';
			var scimoz = ko.views.manager.currentView.scimoz;
			scimoz.replaceSel('');
			scimoz.insertText(scimoz.currentPos, CDN);
			scimoz.gotoPos(scimoz.currentPos + CDN.length);
			ko.views.manager.currentView.setFocus();
		} catch (ex) {
			alert('No file selected');
		}
	}
	
	insertFF = function() {
		if (ko.views.manager.currentView == undefined) {
			return;
		}
		
		try {
			var FF = 'font-family: \'FontAwesome\';';
			var scimoz = ko.views.manager.currentView.scimoz;
			scimoz.replaceSel('');
			scimoz.insertText(scimoz.currentPos, FF);
			scimoz.gotoPos(scimoz.currentPos + FF.length);
			ko.views.manager.currentView.setFocus();
		} catch (ex) {
			alert('No file selected');
		}
	}


}).apply(extensions.FontAwesome);
